name: Python CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0  # Fetch all history to avoid shallow clone issues

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11  # Update to Python 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip  # Ensure pip is up-to-date
        pip install .  # Install project dependencies

    - name: Run Flake8
      run: |
        pip install flake8
        flake8 --config .flake8
    - name: Run tests
      run: |
        pip install flake8
        flake8
        python -m unittest discover -s test -p 'test_*.py'

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
